### ISSUE TITLE
autocomplete

### ISSUE THREAD

**Issue by TrejGun** [Deadly0/final-form-material-ui#28]
yeah i see this lib is not mainteined any more so its kinda useless to write here but for those who is looking for autocomplete bindings
https://trejgun.github.io/articles/bindings-for-using-final-form-with-material-ui-autocomplete

**Comment by lookfirst** [comment]
Also being discussed in this maintained project... https://github.com/lookfirst/mui-rff/issues/36

**Comment by naveennsit** [comment]
@TrejGun https://stackoverflow.com/questions/59832331/why-checkbox-is-not-checked-in-react?noredirect=1#comment105801358_59832331

**Comment by naveennsit** [comment]
@TrejGun  Auto complete not working when we have checkboxes

**Comment by lookfirst** [comment]
FYI, [autocomplete has been added to MUI-RFF](https://github.com/lookfirst/mui-rff#autocomplete---mui-docs) and even uses @naveennsit's usecase in the [example app](https://lookfirst.github.io/mui-rff/)...

**Comment by TrejGun** [comment]
@lookfirst thanks
