### ISSUE TITLE
multiple select

### ISSUE THREAD

**Issue by AlessandroAnnini** [Deadly0/final-form-material-ui#30]
Hi, 
how can I set up a multiple select like the one with the tags in [this example](https://material-ui.com/components/selects/#multiple-select)?

Thanks

**Comment by lookfirst** [comment]
Not to overly plug my own project, but since this one is effectively abandoned, I might as well try to help you. You can do that and more, easily with [MUI-RFF](https://github.com/lookfirst/mui-rff).

**Comment by AlessandroAnnini** [comment]
Thanks man, I used and appreciated your work.
